name = "dog-ceo-worker"
main = "dist/index.mjs"
compatibility_date = "2023-01-03"
compatibility_flags = []

[build]
command = "node build.js"

[miniflare]
kv_persist = true
cache_persist = true

# wrangler kv:namespace create DOGSTUFF

kv_namespaces = [
  { binding = "DOGSTUFF", id = "72a6b702f86f456ebed626ee126f13f3", preview_id = "bf9ab5a9680a46cb9daebf0bd50ab454" }
]

[env.production]
kv_namespaces = [
  { binding = "DOGSTUFF", id = "72a6b702f86f456ebed626ee126f13f3" }
]
