name = "dog-ceo-worker"
main = "dist/index.mjs"
compatibility_date = "2023-01-03"
compatibility_flags = []

[build]
command = "node build.js"

[miniflare]
kv_persist = true
cache_persist = true

kv_namespaces = [
  { binding = "DOGSTUFF", id = "3451ecb077864e0dbd70f4e44566f4f3", preview_id = "bf9ab5a9680a46cb9daebf0bd50ab454" }
]

[env.production]
kv_namespaces = [
  { binding = "DOGSTUFF", id = "3451ecb077864e0dbd70f4e44566f4f3" }
]
